testing: fix ci test

diff --git a/.github/actions/setup/action.yml b/.github/actions/setup/action.yml
--- a/.github/actions/setup/action.yml
+++ b/.github/actions/setup/action.yml
@@ -3,14 +3,22 @@ description: "Setup tooling"
 runs:
   using: "composite"
   steps:
-  - name: Install and setup Dojo
-    run: |
-      curl -L https://install.dojoengine.org | bash
-      source "$HOME/.config/.dojo/env"
-      dojoup install ${{ env.DOJO_VERSION }}
-      sudo mv "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/katana" /usr/local/bin/
-      sudo mv "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/sozo" /usr/local/bin/
-    shell: bash
+    - name: Install and setup Dojo
+      run: |
+        set -e
+        curl -L https://install.dojoengine.org | bash
+        source "$HOME/.config/.dojo/env"
+        dojoup install ${{ env.DOJO_VERSION }}
+
+        if [ ! -f "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/katana" ]; then
+          echo "Katana not found after installation"
+          ls -al "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/"
+          exit 1
+        fi
+
+        sudo mv "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/katana" /usr/local/bin/
+        sudo mv "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/sozo" /usr/local/bin/
+      shell: bash
     # - name: Install dojoup
     #   run: curl -L https://install.dojoengine.org | bash
     #   shell: bash
