chore: local katana-tee deployment

diff --git a/mprocs.local_sepolia.yaml b/mprocs.local_sepolia.yaml
--- a/mprocs.local_sepolia.yaml
+++ b/mprocs.local_sepolia.yaml
@@ -2,53 +2,56 @@ procs:
   initializer:
     cwd: packages/contracts
     env:
-      PROFILE: sepolia
+      L2_PROFILE: sepolia
+      L3_PROFILE: appchain-sepolia
     shell: |
       set -e # exit on error
       source ../../scripts/utils.sh
       #----------------
       # delete targets to wait for a fresh deployment
       echo ">>> Initializing..."
-      rm -rf ../contracts/target/${PROFILE}
-      rm -rf ../starknet/target/${PROFILE}
-      rm -rf ../starknet/data/${PROFILE}
+      rm -rf ../contracts/target/${L3_PROFILE}
+      rm -rf ../starknet/target/${L2_PROFILE}
+      rm -rf ../starknet/data/${L2_PROFILE}
       #----------------
       echo ">>> Waiting for L3 deployment..."
-      wait-on -l ../starknet/target/${PROFILE}/deployed
-      wait-on -l ../contracts/target/${PROFILE}/deployed
-      export APPCHAIN_ADDRESS=$(get_contract_address ${PROFILE} lore-actions_token)
+      wait-on -l ../starknet/target/${L2_PROFILE}/deployed
+      wait-on -l ../contracts/target/${L3_PROFILE}/deployed
+      export APPCHAIN_ADDRESS=$(get_contract_address ${L3_PROFILE} lore-actions_token)
       #----------------
-      # configure L2...
+      # Configure L2 (Starknet)
       #
       cd ../starknet
       source .env.dev-sepolia
-      export PERMIT_TOKEN_ADDRESS=$(get_contract_address ${PROFILE} lore_sn-permit_token)
-      echo ">>> L2: set_messaging_contract(${PILTOVER_ADDRESS})"
-      sozo -P ${PROFILE} execute --wait lore_sn-setup set_messaging_contract ${PILTOVER_ADDRESS}
-      echo ">>> L2: set_appchain_contract(${APPCHAIN_ADDRESS})"
-      sozo -P ${PROFILE} execute --wait lore_sn-setup set_appchain_contract ${APPCHAIN_ADDRESS}
-      echo ">>> L2: PermitConfig:"
-      sozo -P ${PROFILE} model get lore_sn-PermitConfig 1
+      export PERMIT_TOKEN_ADDRESS=$(get_contract_address ${L2_PROFILE} lore_sn-permit_token)
+      echo ">>> L2: [${L2_PROFILE}] set_messaging_contract(${PILTOVER_ADDRESS})"
+      sozo -P ${L2_PROFILE} execute --wait lore_sn-setup set_messaging_contract ${PILTOVER_ADDRESS}
+      echo ">>> L2: [${L2_PROFILE}] set_appchain_contract(${APPCHAIN_ADDRESS})"
+      sozo -P ${L2_PROFILE} execute --wait lore_sn-setup set_appchain_contract ${APPCHAIN_ADDRESS}
+      echo ">>> L2: [${L2_PROFILE}] PermitConfig:"
+      sozo -P ${L2_PROFILE} model get lore_sn-PermitConfig 1
+      touch ../starknet/target/${L2_PROFILE}/initialized
       #----------------
-      # Configure L3
+      # Configure L3 (Katana)
       #
       cd ../contracts
-      echo ">>> L3: set_sn_contract(${PERMIT_TOKEN_ADDRESS})"
-      sozo -P ${PROFILE} execute --wait lore-actions_token set_sn_contract ${PERMIT_TOKEN_ADDRESS}
-      sozo -P ${PROFILE} model get lore-ActionsConfig 1
+      echo ">>> L3: [${L3_PROFILE}] set_sn_contract(${PERMIT_TOKEN_ADDRESS})"
+      sozo -P "${L3_PROFILE}" execute --wait lore-actions_token set_sn_contract ${PERMIT_TOKEN_ADDRESS}
+      echo ">>> L3: [${L3_PROFILE}] ActionsConfig:"
+      sozo -P "${L3_PROFILE}" model get lore-ActionsConfig 1
+      touch ../contracts/target/${L3_PROFILE}/initialized
       #----------------
-      touch ../starknet/target/${PROFILE}/initialized
       echo "👍 Ready!!"
   l2_contracts:
     cwd: packages/starknet
     env:
-      PROFILE: sepolia
+      L2_PROFILE: sepolia
     shell: |
       sleep 1
       set -e # exit on error
       source ../../scripts/utils.sh
       source .env.dev-sepolia
-      export DOJO_WORLD_ADDRESS=$(get_profile_env ${PROFILE} world_address)
+      export DOJO_WORLD_ADDRESS=$(get_profile_env ${L2_PROFILE} world_address)
       echo ">>> Dojo world: [${DOJO_WORLD_ADDRESS}]"
       echo ">>> Deployer: [${DOJO_ACCOUNT_ADDRESS}]"
       #----------------
@@ -56,29 +59,48 @@ procs:
       #
       echo ">>> Deploying contracts..."
       sozo --version
-      sozo -P ${PROFILE} build --typescript
-      sozo -P ${PROFILE} inspect
-      sozo -P ${PROFILE} migrate
+      sozo -P ${L2_PROFILE} build --typescript
+      sozo -P ${L2_PROFILE} inspect
+      sozo -P ${L2_PROFILE} migrate
       #----------------
-      touch ../starknet/target/${PROFILE}/deployed
+      touch ../starknet/target/${L2_PROFILE}/deployed
       echo "👍 L2 Ready!"
   l2_client:
     cwd: packages/client-sn
     env:
-      PROFILE: sepolia
+      L2_PROFILE: sepolia
     shell: |
       sleep 1
       set -e # exit on error
       #----------------
       # wait for L2 to be deployed and initialized
-      wait-on -l ../starknet/target/${PROFILE}/initialized
+      wait-on -l ../starknet/target/${L2_PROFILE}/initialized
       #----------------
       # start client
       bun run dev
+  l2_torii:
+    cwd: packages/starknet
+    env:
+      L2_PROFILE: sepolia
+    shell: |
+      sleep 1
+      set -e # exit on error
+      source ../../scripts/utils.sh
+      export DOJO_WORLD_ADDRESS=$(get_profile_env ${L2_PROFILE} world_address)
+      export RPC_URL=$(get_profile_env ${L2_PROFILE} rpc_url)
+      export PERMIT_TOKEN_ADDRESS=$(get_contract_address ${L2_PROFILE} lore_sn-permit_token)
+      echo ">>> Dojo world: [${DOJO_WORLD_ADDRESS}]"
+      echo ">>> Permit token: [${PERMIT_TOKEN_ADDRESS}]"
+      #----------------
+      # start Torii
+      torii --version
+      torii --http.cors_origins "*" \
+        --world ${DOJO_WORLD_ADDRESS} \
+        --rpc ${RPC_URL} \
+        --indexing.contracts erc721:${PERMIT_TOKEN_ADDRESS}
   l3_katana:
     cwd: packages/starknet
     env:
-      PROFILE: sepolia
       KATANA_TEE_BIN: ./bin/katana-tee
       KATANA_PORT: "6969"
       CHAIN_CONFIG_PATH: ./data/dev-sepolia/chain-config
@@ -112,30 +134,29 @@ procs:
   l3_contracts:
     cwd: packages/contracts
     env:
-      PROFILE: appchain-sepolia
+      L3_PROFILE: appchain-sepolia
       KATANA_PORT: "6969"
       KATANA_CHAIN_ID: MY_APPCHAIN_DEV
     shell: |
       sleep 1
       set -e # exit on error
       source ../../scripts/utils.sh
-      export DOJO_WORLD_ADDRESS=$(get_profile_env ${PROFILE} world_address)
+      export DOJO_WORLD_ADDRESS=$(get_profile_env ${L3_PROFILE} world_address)
       echo ">>> Dojo world: [${DOJO_WORLD_ADDRESS}]"
       #----------------
       # wait for katana_l3 init
       wait-port ${KATANA_PORT}
       echo ">>> Deploying contracts..."
-      sozo -P ${PROFILE} build
-      # sozo -P ${PROFILE} inspect
-      # echo SKIPPING MIGRATONS
-      sozo -P ${PROFILE} migrate
+      sozo -P ${L3_PROFILE} build
+      sozo -P ${L3_PROFILE} inspect
+      sozo -P ${L3_PROFILE} migrate
       #----------------
-      touch ../contracts/target/${PROFILE}/deployed
+      touch ../contracts/target/${L3_PROFILE}/deployed
       echo "👍 L2 Ready!"
   saya:
     cwd: packages/starknet
     env:
-      PROFILE: sepolia
+      L2_PROFILE: sepolia
       SAYA_TEE_BIN: ./bin/saya-tee
       STARKNET_RPC_URL: https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_9
       KATANA_RPC: http://localhost:6969
@@ -147,11 +168,11 @@ procs:
       source .env.dev-sepolia
       #----------------
       # wait for L2 and L3 to be deployed and initialized
-      wait-on -l ../starknet/target/${PROFILE}/initialized
+      wait-on -l ../starknet/target/${L2_PROFILE}/initialized
       #----------------
       # gather data...
       #
-      export DATA_PATH=./data/${PROFILE}
+      export DATA_PATH=./data/${L2_PROFILE}
       export PILTOVER_ADDRESS=$(grep '^core_contract' ${CHAIN_CONFIG_PATH}/config.toml | head -1 | awk -F'"' '{print $2}')
       echo ">>> KATANA_RPC: [${KATANA_RPC}]"
       echo ">>> PILTOVER_ADDRESS: [${PILTOVER_ADDRESS}]"
@@ -190,15 +211,15 @@ procs:
   # torii:
   #   cwd: packages/contracts
   #   env:
-  #     PROFILE: sepolia
+  #     L2_PROFILE: sepolia
   #     KATANA_L3_PORT: "6969"
   #   shell: |
   #     sleep 1
   #     set -e # exit on error
   #     source ../../scripts/utils.sh
-  #     export DOJO_WORLD_ADDRESS=$(get_profile_env ${PROFILE} world_address)
-  #     export GAME_TOKEN_ADDRESS=$(get_contract_address ${PROFILE} lore-game_token)
-  #     export TRAIL_TOKEN_ADDRESS=$(get_contract_address ${PROFILE} lore-trail_token)
+  #     export DOJO_WORLD_ADDRESS=$(get_profile_env ${L2_PROFILE} world_address)
+  #     export GAME_TOKEN_ADDRESS=$(get_contract_address ${L2_PROFILE} lore-game_token)
+  #     export TRAIL_TOKEN_ADDRESS=$(get_contract_address ${L2_PROFILE} lore-trail_token)
   #     echo ">>> Dojo world: [${DOJO_WORLD_ADDRESS}]"
   #     echo ">>> Game token: [${GAME_TOKEN_ADDRESS}]"
   #     echo ">>> Trail token: [${TRAIL_TOKEN_ADDRESS}]"
