chore: moved saya tests to new profile: saya-test

diff --git a/mprocs.local_saya-test.yaml b/mprocs.local_saya-test.yaml
--- a/mprocs.local_saya-test.yaml
+++ b/mprocs.local_saya-test.yaml
@@ -2,7 +2,7 @@ procs:
   initializer:
     cwd: packages/contracts
     env:
-      PROFILE: dev
+      PROFILE: saya-test
     shell: |
       set -e # exit on error
       source ../../scripts/utils.sh
@@ -55,7 +55,7 @@ procs:
   l2_contracts:
     cwd: packages/starknet
     env:
-      PROFILE: dev
+      PROFILE: saya-test
       KATANA_L2_PORT: "50000"
       KATANA_L3_BIN: ./bin/katana-1.7.0-snos.4
       KATANA_L3_CHAIN: katana-l3
@@ -125,7 +125,7 @@ procs:
   l3_katana:
     cwd: packages/starknet
     env:
-      PROFILE: dev
+      PROFILE: saya-test
       KATANA_L3_BIN: ./bin/katana-1.7.0-snos.4
       KATANA_L3_PORT: "5050"
       BLOCK_TIME: "30000"
@@ -157,7 +157,7 @@ procs:
   l3_contracts:
     cwd: packages/contracts
     env:
-      PROFILE: dev
+      PROFILE: saya-test
       KATANA_L3_PORT: "5050"
     shell: |
       sleep 1
@@ -175,13 +175,10 @@ procs:
       #----------------
       touch ../contracts/target/${PROFILE}/deployed
       echo "👍 L2 Ready!"
-      #----------------
-      # echo "👀 Watching..."
-      # bun run dev:watch
   saya:
     cwd: packages/starknet
     env:
-      PROFILE: dev
+      PROFILE: saya-test
       RUST_LOG: saya=debug
       KATANA_L2_RPC: http://localhost:50000
       KATANA_L3_RPC: http://localhost:5050
@@ -217,35 +214,35 @@ procs:
         --rollup-rpc ${KATANA_L3_RPC} \
         --mock-snos-from-pie \
         --mock-layout-bridge-program-hash 0x43c5c4cc37c4614d2cf3a833379052c3a38cd18d688b617e2c720e8f941cb8
-  torii:
-    cwd: packages/contracts
-    env:
-      PROFILE: dev
-      KATANA_L3_PORT: "5050"
-    shell: |
-      sleep 1
-      set -e # exit on error
-      source ../../scripts/utils.sh
-      export DOJO_WORLD_ADDRESS=$(get_profile_env ${PROFILE} world_address)
-      export GAME_TOKEN_ADDRESS=$(get_contract_address ${PROFILE} lore-game_token)
-      export TRAIL_TOKEN_ADDRESS=$(get_contract_address ${PROFILE} lore-trail_token)
-      echo ">>> Dojo world: [${DOJO_WORLD_ADDRESS}]"
-      echo ">>> Game token: [${GAME_TOKEN_ADDRESS}]"
-      echo ">>> Trail token: [${TRAIL_TOKEN_ADDRESS}]"
-      #----------------
-      wait-port ${KATANA_L3_PORT}
-      #----------------
-      # start Torii
-      torii --version
-      torii --http.cors_origins "*" \
-        --indexing.contracts erc721:${GAME_TOKEN_ADDRESS},erc721:${TRAIL_TOKEN_ADDRESS}
-  client:
-    cwd: packages/client
-    env:
-      KATANA_L3_PORT: "5050"
-    shell: |
-      sleep 1
-      #----------------
-      wait-port ${KATANA_L3_PORT}
-      #----------------
-      bun run dev
+  # torii:
+  #   cwd: packages/contracts
+  #   env:
+  #     PROFILE: saya-test
+  #     KATANA_L3_PORT: "5050"
+  #   shell: |
+  #     sleep 1
+  #     set -e # exit on error
+  #     source ../../scripts/utils.sh
+  #     export DOJO_WORLD_ADDRESS=$(get_profile_env ${PROFILE} world_address)
+  #     export GAME_TOKEN_ADDRESS=$(get_contract_address ${PROFILE} lore-game_token)
+  #     export TRAIL_TOKEN_ADDRESS=$(get_contract_address ${PROFILE} lore-trail_token)
+  #     echo ">>> Dojo world: [${DOJO_WORLD_ADDRESS}]"
+  #     echo ">>> Game token: [${GAME_TOKEN_ADDRESS}]"
+  #     echo ">>> Trail token: [${TRAIL_TOKEN_ADDRESS}]"
+  #     #----------------
+  #     wait-port ${KATANA_L3_PORT}
+  #     #----------------
+  #     # start Torii
+  #     torii --version
+  #     torii --http.cors_origins "*" \
+  #       --indexing.contracts erc721:${GAME_TOKEN_ADDRESS},erc721:${TRAIL_TOKEN_ADDRESS}
+  # client:
+  #   cwd: packages/client
+  #   env:
+  #     KATANA_L3_PORT: "5050"
+  #   shell: |
+  #     sleep 1
+  #     #----------------
+  #     wait-port ${KATANA_L3_PORT}
+  #     #----------------
+  #     bun run dev
