chore: local saya setup

diff --git a/mprocs.local_saya.yaml b/mprocs.local_saya.yaml
--- a/mprocs.local_saya.yaml
+++ b/mprocs.local_saya.yaml
@@ -1,25 +1,44 @@
 procs:
+  initializer:
+    cwd: packages/starknet
+    env:
+      PROFILE: dev
+    shell: |
+      echo ">>> Initializing..."
+      export DATA_PATH=./data/${PROFILE}
+      rm -rf ${DATA_PATH}
+      # rm -f ./manifest_${PROFILE}.json
+      # rm -f ../contracts/manifest_${PROFILE}.json
+      echo ">>> Done!"
   l2_katana:
     cwd: packages/starknet
+    env:
+      KATANA_L2_PORT: "50000"
     shell: |
-      echo "Starting L2 Katana... [$KATANA_L2_RPC]"
+      echo "Starting L2 Katana on port [${KATANA_L2_PORT}]..."
       katana --version
-      katana --dev --dev.no-fee --http.port 50000
+      katana --dev --dev.no-fee --http.port ${KATANA_L2_PORT}
   l2_contracts:
     cwd: packages/starknet
     env:
       PROFILE: dev
+      KATANA_L2_PORT: "50000"
       KATANA_L2_RPC: http://localhost:50000
-      DOJO_WORLD_ADDRESS: 0x03bd2ce4af00a298fb73f997972c6cc39a6cab58f6bf9a1d16b98431da1b3dc7
+      KATANA_L3_BIN: ./bin/katana_l3
+      SETTLEMENT_ACCOUNT_ADDRESS: 0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec
+      SETTLEMENT_ACCOUNT_PRIVATE_KEY: 0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912
       FACT_REGISTRY_MOCK_ADDRESS: 0x0574b73e6db9e1d7e875a15c52ac9de7b62873c5702eeedede54c8004fa405cb
-      KATANA_L3_DATA_PATH: temp/katana-l3
     shell: |
+      sleep 1
+      set -e # exit on error
+      source ../../scripts/utils.sh
+      export DOJO_WORLD_ADDRESS=$(get_profile_env ${PROFILE} world_address)
+      echo ">>> Dojo world: [${DOJO_WORLD_ADDRESS}]"
       #----------------
       # based on:
       # https://github.com/glihm/starknet-messaging-dev/tree/l2-l3-saya?tab=readme-ov-file#setup-the-l2-starknet
       #
       echo ">>> Deploying L2 mocked fact registry contract..."
-      rm -rf temp
       sozo -P ${PROFILE} build
       sozo declare target/dev/lore_strk_fact_registry_mock.contract_class.json \
         --katana-account katana0 \
@@ -31,134 +50,155 @@ procs:
       # will output: FACT_REGISTRY_MOCK_ADDRESS
       echo "!!! Validate: FACT_REGISTRY_MOCK_ADDRESS=${FACT_REGISTRY_MOCK_ADDRESS}"
       #----------------
+      # katana_l3 init
+      #
       echo ">>> Creating Katana L3 config..."
-      mkdir -p ${KATANA_L3_DATA_PATH}
-      ./bin/katana_l3 init \
+      export DATA_PATH=./data/${PROFILE}
+      mkdir -p ${DATA_PATH}
+      ${KATANA_L3_BIN} init \
         --settlement-chain ${KATANA_L2_RPC} \
         --id katana-l3 \
-        --settlement-account-private-key 0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 \
-        --settlement-account-address 0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec \
+        --settlement-account-private-key ${SETTLEMENT_ACCOUNT_PRIVATE_KEY} \
+        --settlement-account-address ${SETTLEMENT_ACCOUNT_ADDRESS} \
         --settlement-facts-registry ${FACT_REGISTRY_MOCK_ADDRESS} \
-        --output-path ${KATANA_L3_DATA_PATH}
+        --output-path ${DATA_PATH}
       # will output: PILTOVER_ADDRESS
       #----------------
-      # verify piltover address
-      PILTOVER_ADDRESS=$(grep '^core_contract' ${KATANA_L3_DATA_PATH}/config.toml | sed -E 's/core_contract = "([^"]+)"/\1/')
+      # validate piltover address
+      #
+      PILTOVER_ADDRESS=$(grep '^core_contract' ${DATA_PATH}/config.toml | sed -E 's/core_contract = "([^"]+)"/\1/')
       echo "!!! Validate: PILTOVER_ADDRESS=${PILTOVER_ADDRESS}"
       #----------------
       # deploy contracts...
-      echo ">>> Waiting for L2 Katana to start..."
+      #
+      wait-port ${KATANA_L2_PORT}
       echo ">>> Deploying contracts..."
-      wait-port 50000
       sozo -P ${PROFILE} inspect
       sozo -P ${PROFILE} migrate
       #----------------
-      # deploy contracts...
-      echo ">>> Initialize contracts..."
+      # set_messaging_contract()
+      #
+      echo ">>> L2: set_messaging_contract(${PILTOVER_ADDRESS})"
       sozo -P ${PROFILE} execute --wait lore_strk-actions_strk set_messaging_contract ${PILTOVER_ADDRESS}
-      # sozo -P ${PROFILE} execute --wait lore_strk-actions_strk set_appchain_contract ${APPCHAIN_ADDRESS}
-      sozo -P $PROFILE model get lore_strk-MessagingConfig 1
+      sozo -P ${PROFILE} model get lore_strk-MessagingConfig 1
       #----------------
+      # set_appchain_contract()
+      #
+      cd ../contracts
+      export APPCHAIN_ADDRESS=$(get_contract_address ${PROFILE} lore-actions_lore)
+      echo ">>> L2: set_appchain_contract(${APPCHAIN_ADDRESS})"
+      cd ../starknet
+      sozo -P ${PROFILE} execute --wait lore_strk-actions_strk set_appchain_contract ${APPCHAIN_ADDRESS}
+      sozo -P ${PROFILE} model get lore_strk-MessagingConfig 1
+      #----------------
+      #
       echo "👍 Done!"
-
-
-  # l3_katana:
-  #   cwd: packages/contracts
-  #   shell: |
-  #     export CHAIN_ID=KATANA_DA_LOCAL
-  #     export CHAIN_CONFIG_PATH=./katana-da-sepolia-config/config.toml
-  #     katana --version
-  #     katana --chain-id $CHAIN_ID \
-  #       --dev --dev.no-fee \
-  #       --http.cors_origins "*" \
-  #       --cartridge.controllers --cartridge.paymaster \
-  #       --block-time 30000 --sequencing.block-max-cairo-steps 16000000 \
-  #       --config $CHAIN_CONFIG_PATH
-  # l3_contracts:
-  #   cwd: packages/contracts
-  #   shell: |
-  #     wait-port 5050
-  #     bun run dev:watch
-  # saya:
-  #   cwd: packages/starknet
-  #   shell: |
-  #     # wait for katana to start
-  #     wait-port 5050
-  #     # start Saya
-  #     pwd
-  #     source .env.persistent.sepolia
-  #     eval $SAYA_CMD --version
-  #     eval $SAYA_CMD persistent start
-
-
-
-
-  # client:
-  #   cwd: packages/client
-  #   shell: bun run dev
-  # torii:
-  #   cwd: packages/contracts
-  #   shell: |
-  #     export GAME_TOKEN_ADDRESS=0x6962da1f222d4c4209110aa24d0482c672678aa22fa91975b3bac65c5e09d67
-  #     export TRAIL_TOKEN_ADDRESS=0x97e9a41ae85099766f59ba50486b57b7236030389e4ac31ccd46d75039de2a
-  #     # wait for katana to start
-  #     wait-port 5050
-  #     # start Torii
-  #     torii --version
-  #     torii --http.cors_origins "*" \
-  #       --world 0x06edbd6fb23929a69ff0fef81f09e3c7689ac01050e4ddb43dc6273f18b37403` \
-  #       --indexing.contracts erc721:$GAME_TOKEN_ADDRESS,erc721:$TRAIL_TOKEN_ADDRESS
-
-
-
-
-
-
-
-
-
-  # l2_contracts:
-  #   cwd: packages/starknet
-  #   env:
-  #     KATANA_L2_RPC: http://localhost:50000
-  #     FACT_REGISTRY_MOCK_ADDRESS: 0x03b041d3612bc1f29331e8de56945a1f0a580001e59a7c93e81d69e07981027b
-  #     MESSAGING_REPO_PATH: temp/starknet-messaging-dev
-  #     KATANA_L3_DATA_PATH: temp/data/katana-l3
-  #   shell: |
-  #     echo "\nBuild messaging..."
-  #     rm -rf temp
-  #     git clone https://github.com/glihm/starknet-messaging-dev.git ${MESSAGING_REPO_PATH}
-  #     mkdir -p ${KATANA_L3_DATA_PATH}
-  #     cd ${MESSAGING_REPO_PATH}/cairo
-  #     git checkout l2-l3-saya
-  #     scarb build
-  #     cd -
-  #     #----------------
-  #     echo "\nWaiting for L2 Katana to start..."
-  #     wait-port 50000
-  #     echo "Deploying L2 mocked fact registry contract..."
-  #     sozo declare ${MESSAGING_REPO_PATH}/cairo/target/dev/sn_msg_dev_fact_registry_mock.contract_class.json \
-  #       --katana-account katana0 \
-  #       --rpc-url ${KATANA_L2_RPC}
-  #     sozo deploy 0x01d42b549cf7a09fc7ffdd176a0addf6e7d26d81678240597e58f1103952faf8 \
-  #       --katana-account katana0 \
-  #       --salt 0x1234 \
-  #       --rpc-url ${KATANA_L2_RPC}
-  #     # will output: FACT_REGISTRY_MOCK_ADDRESS
-  #     #----------------
-  #     # deploy contracts...
-  #     # TODO
-  #     #----------------
-  #     echo "\nDeploying L2 contracts..."
-  #     pwd
-  #     ./bin/katana_l3 init \
-  #       --settlement-chain ${KATANA_L2_RPC} \
-  #       --id katana-l3 \
-  #       --settlement-account-private-key 0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 \
-  #       --settlement-account-address 0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec \
-  #       --settlement-facts-registry ${FACT_REGISTRY_MOCK_ADDRESS} \
-  #       --output-path ${KATANA_L3_DATA_PATH}
-  #     #----------------
-  #     # verify piltover address
-  #     PILTOVER_ADDRESS=$(grep '^core_contract' ${KATANA_L3_DATA_PATH}/config.toml | sed -E 's/core_contract = "([^"]+)"/\1/')
-  #     echo "PILTOVER_ADDRESS=${PILTOVER_ADDRESS}"
+  l3_katana:
+    cwd: packages/starknet
+    env:
+      PROFILE: dev
+      KATANA_L3_BIN: ./bin/katana_l3
+      KATANA_L3_PORT: "5050"
+      BLOCK_TIME: "30000"
+      MAX_CAIRO_STEPS: "16000000"
+    shell: |
+      sleep 1
+      #----------------
+      # wait for katana_l3 init file
+      #
+      sleep 1
+      export DATA_PATH=./data/${PROFILE}
+      echo ">>> Waiting for L3 init config... [${DATA_PATH}/config.toml]"
+      wait-on ${DATA_PATH}/config.toml
+      #----------------
+      # start katana L3...
+      #
+      echo ">>> Starting L3 Katana on port [${KATANA_L3_PORT}]..."
+      ${KATANA_L3_BIN} --version
+      ${KATANA_L3_BIN} \
+        --dev --dev.no-fee --dev.accounts 10 \
+        --http.cors_origins "*" \
+        --http.port ${KATANA_L3_PORT} \
+        --cartridge.controllers --cartridge.paymaster \
+        --chain ${DATA_PATH} \
+        # --block-time ${BLOCK_TIME} --sequencing.block-max-cairo-steps ${MAX_CAIRO_STEPS}
+  l3_contracts:
+    cwd: packages/contracts
+    env:
+      KATANA_L3_PORT: "5050"
+    shell: |
+      sleep 1
+      #----------------
+      # wait for katana_l3 init
+      wait-port ${KATANA_L3_PORT}
+      #----------------
+      bun run dev:watch
+  saya:
+    cwd: packages/starknet
+    env:
+      PROFILE: dev
+      RUST_LOG: saya=debug
+      KATANA_L2_RPC: http://localhost:50000
+      KATANA_L3_RPC: http://localhost:5050
+      KATANA_L2_PORT: "50000"
+      KATANA_L3_PORT: "5050"
+      SETTLEMENT_ACCOUNT_ADDRESS: 0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec
+      SETTLEMENT_ACCOUNT_PRIVATE_KEY: 0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912
+    shell: |
+      sleep 1
+      set -e # exit on error
+      #----------------
+      export DATA_PATH=./data/${PROFILE}
+      echo ">>> Waiting for L3 init config... [${DATA_PATH}/config.toml]"
+      wait-on ${DATA_PATH}/config.toml
+      PILTOVER_ADDRESS=$(grep '^core_contract' ${DATA_PATH}/config.toml | sed -E 's/core_contract = "([^"]+)"/\1/')
+      echo ">>> PILTOVER_ADDRESS: [${PILTOVER_ADDRESS}]"
+      #----------------
+      # wait for katana_l3 init
+      wait-port ${KATANA_L2_PORT}
+      wait-port ${KATANA_L3_PORT}
+      #----------------
+      # sytart saya
+      #
+      export DB_DIR=${DATA_PATH}
+      saya --version
+      saya persistent start \
+        --settlement-rpc ${KATANA_L2_RPC} \
+        --settlement-piltover-address ${PILTOVER_ADDRESS} \
+        --settlement-account-address ${SETTLEMENT_ACCOUNT_ADDRESS} \
+        --settlement-account-private-key ${SETTLEMENT_ACCOUNT_PRIVATE_KEY} \
+        --rollup-rpc ${KATANA_L3_RPC} \
+        --mock-snos-from-pie \
+        --mock-layout-bridge-program-hash 0x43c5c4cc37c4614d2cf3a833379052c3a38cd18d688b617e2c720e8f941cb8
+  client:
+    cwd: packages/client
+    env:
+      KATANA_L3_PORT: "5050"
+    shell: |
+      sleep 1
+      #----------------
+      wait-port ${KATANA_L3_PORT}
+      #----------------
+      bun run dev
+  torii:
+    cwd: packages/contracts
+    env:
+      PROFILE: dev
+      KATANA_L3_PORT: "5050"
+    shell: |
+      sleep 1
+      set -e # exit on error
+      source ../../scripts/utils.sh
+      export DOJO_WORLD_ADDRESS=$(get_profile_env ${PROFILE} world_address)
+      export GAME_TOKEN_ADDRESS=$(get_contract_address ${PROFILE} lore-game_token)
+      export TRAIL_TOKEN_ADDRESS=$(get_contract_address ${PROFILE} lore-trail_token)
+      echo ">>> Dojo world: [${DOJO_WORLD_ADDRESS}]"
+      echo ">>> Game token: [${GAME_TOKEN_ADDRESS}]"
+      echo ">>> Trail token: [${TRAIL_TOKEN_ADDRESS}]"
+      #----------------
+      wait-port ${KATANA_L3_PORT}
+      #----------------
+      # start Torii
+      torii --version
+      torii --http.cors_origins "*" \
+        --indexing.contracts erc721:${GAME_TOKEN_ADDRESS},erc721:${TRAIL_TOKEN_ADDRESS}
