fix: config messaging in dev:saya

diff --git a/mprocs.local_saya.yaml b/mprocs.local_saya.yaml
--- a/mprocs.local_saya.yaml
+++ b/mprocs.local_saya.yaml
@@ -1,15 +1,36 @@
 procs:
   initializer:
-    cwd: packages/starknet
+    cwd: packages/contracts
     env:
       PROFILE: dev
     shell: |
+      set -e # exit on error
+      source ../../scripts/utils.sh
+      #----------------
+      # delete targets to wait for a fresh deployment
       echo ">>> Initializing..."
-      export DATA_PATH=./data/${PROFILE}
-      rm -rf ${DATA_PATH}
-      # rm -f ./manifest_${PROFILE}.json
-      # rm -f ../contracts/manifest_${PROFILE}.json
-      echo ">>> Done!"
+      rm -rf ./target/${PROFILE}
+      rm -rf ../starknet/target/${PROFILE}
+      rm -rf ../starknet/data/${PROFILE}
+      #----------------
+      # set_appchain_contract()
+      #
+      echo ">>> Waiting for L3 deployment..."
+      wait-on -l ./target/${PROFILE}/deployed
+      export APPCHAIN_ADDRESS=$(get_contract_address ${PROFILE} lore-actions_lore)
+      #----------------
+      echo ">>> L2: set_appchain_contract(${APPCHAIN_ADDRESS})"
+      cd ../starknet
+      sozo -P ${PROFILE} execute --wait lore_strk-actions_strk set_appchain_contract ${APPCHAIN_ADDRESS}
+      sozo -P ${PROFILE} model get lore_strk-MessagingConfig 1
+      export SN_ADDRESS=$(get_contract_address ${PROFILE} lore_strk-actions_strk)
+      #----------------
+      echo ">>> L3: set_sn_contract(${SN_ADDRESS})"
+      cd ../contracts
+      sozo -P ${PROFILE} execute --wait lore-actions_lore set_sn_contract ${SN_ADDRESS}
+      sozo -P ${PROFILE} model get lore-ActionsConfig 1
+      #----------------
+      echo "👍 Done!"
   l2_katana:
     cwd: packages/starknet
     env:
@@ -75,6 +96,7 @@ procs:
       echo ">>> Deploying contracts..."
       sozo -P ${PROFILE} inspect
       sozo -P ${PROFILE} migrate
+      touch target/${PROFILE}/deployed
       #----------------
       # set_messaging_contract()
       #
@@ -82,16 +104,6 @@ procs:
       sozo -P ${PROFILE} execute --wait lore_strk-actions_strk set_messaging_contract ${PILTOVER_ADDRESS}
       sozo -P ${PROFILE} model get lore_strk-MessagingConfig 1
       #----------------
-      # set_appchain_contract()
-      #
-      cd ../contracts
-      export APPCHAIN_ADDRESS=$(get_contract_address ${PROFILE} lore-actions_lore)
-      echo ">>> L2: set_appchain_contract(${APPCHAIN_ADDRESS})"
-      cd ../starknet
-      sozo -P ${PROFILE} execute --wait lore_strk-actions_strk set_appchain_contract ${APPCHAIN_ADDRESS}
-      sozo -P ${PROFILE} model get lore_strk-MessagingConfig 1
-      #----------------
-      #
       echo "👍 Done!"
   l3_katana:
     cwd: packages/starknet
@@ -109,7 +121,7 @@ procs:
       sleep 1
       export DATA_PATH=./data/${PROFILE}
       echo ">>> Waiting for L3 init config... [${DATA_PATH}/config.toml]"
-      wait-on ${DATA_PATH}/config.toml
+      wait-on -l ${DATA_PATH}/config.toml
       #----------------
       # start katana L3...
       #
@@ -150,7 +162,7 @@ procs:
       #----------------
       export DATA_PATH=./data/${PROFILE}
       echo ">>> Waiting for L3 init config... [${DATA_PATH}/config.toml]"
-      wait-on ${DATA_PATH}/config.toml
+      wait-on -l ${DATA_PATH}/config.toml
       PILTOVER_ADDRESS=$(grep '^core_contract' ${DATA_PATH}/config.toml | sed -E 's/core_contract = "([^"]+)"/\1/')
       echo ">>> PILTOVER_ADDRESS: [${PILTOVER_ADDRESS}]"
       #----------------
